### PR TITLE
[WIP] .NET Core SDK preview2 and .NET Core 1.0 RTM

### PR DESCRIPTION
**Pull request by enricosada**
as @Andrea 's request :smile: 

i get an error

```

Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'SDL2.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at SDL.SDLInitNative.SDL_Init(UInt32 flags)
   at Treatz.main()
   at <StartupCode$Treatz>.$Treatz.main@()
```

to try it:
- install .net sdk preview2 ( http://dot.net )
- from root
  - `dotnet restore`
  - `cd src/Treatz`
  - `dotnet build` (it build both project)
  - `dotnet run` (run it!, it does build already if needed, so dotnet build is not needed)

### CODE REVIEW

**Comment by enricosada** [comment]
so because i dont know yet how native works (i'll check) i do that manually after build

i copy native dll from the nuget cache ( `C:\Users\username\.nuget\packages\sdl2.redist\2.0.3\build\native\bin\x64\dynamic\SDL2.dll` ) to build directory `.\src\Treatz\bin\Debug\netcoreapp1.0` (where is `Treatz.dll`, to see paths use `-v` like `dotnet -v run`) 

then a window appear

image

after it's closed i see error:

```
Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at SDLSurface.SDLSurfaceNative.SDL_ConvertSurfaceFormat(IntPtr src, UInt32 pixel_format, UInt32 flags)
   at SDLSurface.loadBmp(UInt32 pixelFormat, String fileName)
   at Treatz.main()
   at <StartupCode$Treatz>.$Treatz.main@()
```

i really dont know how to debug that, of if more deps are needed

**Comment by Andrea** [comment]
will look at in a few hours

**Comment by enricosada** [comment]
i'll check about native, but i am pretty sure it need a special directory structure inside the nuget package to get it by default (it's a new feature of nuget). or maybe i dont know how :smile:

**Comment by Andrea** [comment]
finally just tried it with same results... investigating

**Comment by enricosada** [comment]
@Andrea you can ask https://gitter.im/dotnet/cli or the `coreclr` and `corefx`.
there is also a slack channel about asp.net core, maybe there too. 

last possibility is, to open an issue in dotnet/cli repo. if you can minimize the repro, usually they answer fast. 
you can use [console template](https://github.com/dotnet/netcorecli-fsc/tree/master/examples/preview2/console) for a simple console app.
I'll try to continue later this pr if a have a bit of time, to create a minimal repro

**Comment by Andrea** [comment]
so, I had to do an update to VS so that it will support netcore, after following some errors that required me to include framework 4.5.2 in both sdlfs and Treatz ( it kind of sounds like I shouldn't need this) but I thought I would try anyway... I get these errors

```
Microsoft.FSharp.Core.netcore 1.0.0-alpha-160629 is not compatible with .NETFramework,Version=v4.5.2 (win-x86).             
Microsoft.FSharp.Core.netcore 1.0.0-alpha-160629 is not compatible with .NETFramework,Version=v4.5.2.
Some packages are not compatible with .NETFramework,Version=v4.5.2.             
```

the changes I made are here https://github.com/Andrea/Treatz/commits/enricosada-netcore 
will look again when I can

**Pull request closed without merging**
